# Generated by Django 2.1.7 on 2019-02-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0002_auto_20190228_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='raise',
            name='base64',
            field=models.TextField(default='-'),
        ),
    ]
