# Generated by Django 2.1.7 on 2019-03-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0003_raise_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='codigo',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='raise',
            name='codigo',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='scale',
            name='codigo',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
