# Generated by Django 2.1.7 on 2019-03-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0009_auto_20190308_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise',
            name='codigo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
