# Generated by Django 2.1.7 on 2019-03-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0011_auto_20190308_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raise',
            name='codigo',
        ),
    ]
