# Generated by Django 2.1.7 on 2019-03-08 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0013_auto_20190308_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scales.Scale'),
        ),
    ]
