# Generated by Django 2.1.7 on 2019-03-08 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0015_auto_20190308_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
