# Generated by Django 2.1.7 on 2019-03-09 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0016_auto_20190308_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scales.Scale'),
        ),
    ]
