# Generated by Django 2.1.7 on 2019-03-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0017_auto_20190309_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise',
            name='scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scales.Scale'),
        ),
    ]
