# Generated by Django 2.1.7 on 2019-03-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0018_auto_20190309_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raise',
            old_name='scale',
            new_name='scale_id',
        ),
    ]
