# Generated by Django 2.1.7 on 2019-03-12 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0021_auto_20190312_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
