# Generated by Django 2.1.7 on 2019-03-12 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0022_auto_20190312_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scales.Scale'),
        ),
    ]
