# Generated by Django 2.1.7 on 2019-03-12 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0023_date_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='scale',
        ),
        migrations.AddField(
            model_name='date',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scales.Point'),
        ),
    ]
